# Generated by Django 4.2.16 on 2024-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=150)),
                ('price', models.FloatField(max_length=150)),
            ],
        ),
    ]
